Todo.Web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Todo.Web.Clients.Interfaces;
using Todo.Web.Clients.Models;
using Todo.Web.Models;

namespace Todo.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserClient _userClient;

        public LoginController(IUserClient userClient)
        {
            _userClient = userClient;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index([Bind("Name, Password")] LoginViewModel model)
        {
            var userId = await _userClient.ValidatePassword(new Clients.Models.ValidatePasswordInputModel
            {
                Name = model.Name!,
                Password = model.Password!
            });

            if (userId is null || userId <= 0)
            {
                ModelState.AddModelError("Password", "Invalid password"); 
                return View(model);
            }

            var user = await _userClient.GetById(userId);
            if (user is null)
            {
                ModelState.AddModelError("Password", "Invalid password");
                return View(model);
            }

            await SignInAsync(user.Id, model.Name!, user.IsAdmin);

            return RedirectToAction(
                nameof(HomeController.Index), 
                "Home");
        }

        [HttpGet]
        public IActionResult Register()
        {
            ViewBag.TaskList = 12341;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromRoute] string id, RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(ModelState);
            }

            if (model.Password != model.RepeatPassword)
            {
                ModelState.TryAddModelError(
                    nameof(model.RepeatPassword), 
                    "Passwords dont match");

                return View(model);
            }

            try
            {
                var userId = await _userClient.CreateUser(new Clients.Models.CreateUserInputModel
                {
                    IsAdmin = false,
                    Name = model.Name!,
                    Password = model.Password!
                });

                await SignInAsync(userId, model.Name!, false);
            }
            catch(Exception ex)
            {
                ModelState.TryAddModelError(
                    string.Empty,
                    "Passwords dont match");

                return View(model);
            }

            return RedirectToAction(
                nameof(HomeController.Index),
                "Home");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            var user = await _userClient.GetById(
                int.Parse(HttpContext.User.FindFirst("userId")?.Value ?? string.Empty));

            await HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task SignInAsync(int? userId, string userName, bool isAdmin)
        {
            var claimsIdentity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, "name", "role");
            claimsIdentity.AddClaim(new Claim("name", userName));
            claimsIdentity.AddClaim(new Claim("userId", userId?.ToString() ?? string.Empty));
            claimsIdentity.AddClaim(new Claim("role", isAdmin ? "Administrator" : "User"));

            var principal = new ClaimsPrincipal(claimsIdentity);

            await HttpContext.SignInAsync(principal);
        }
    }
}

Todo.Web/Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Todo.Web.Clients.Interfaces;
using Todo.Web.Models;

namespace Todo.Web.Controllers
{
    [Authorize]
    public class TodosController : Controller
    {
        private readonly ITodoListClient _todosClient;

        public TodosController(ITodoListClient client)
        {
            _todosClient = client;
        }

        // GET: Todos
        public async Task<IActionResult> Index()
        {
            int userId = int.Parse(User.FindFirst("userId")!.Value!);
            var todosList = await _todosClient.GetAll(userId);

            var viewModels = todosList
                .Select(e => new TodoListViewModel { 
                    Id = e.Id, 
                    Description = e.Description, 
                    IsActive = e.IsActive, 
                    NumberOfTasks = e.NumberOfTasks})
                .ToArray();

            return View(viewModels);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description")] CreateTodoListViewModel todoListViewModel)
        {
            if (ModelState.IsValid)
            {
                int userId = int.Parse(User.FindFirst("userId")!.Value!);
                await _todosClient.CreateTodo(new Clients.Models.TodoList.CreateTodoListInputModel
                {
                    Description = todoListViewModel.Description!
                }, userId);

                return RedirectToAction(nameof(Index));
            }

            return View(todoListViewModel);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var list = await _todosClient.GetById(id);

            if (list == null)
            {
                return NotFound();
            }

            // Redirect to the TodoTaskController's Index with the list ID
            return RedirectToAction("Index", "Task", new { 
                todoListId = list.Id, 
                todoDescription = list.Description, 
                todoIsActive = list.IsActive, 
                todoNumOfTasks = list.NumberOfTasks });
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var list = await _todosClient.GetById(id);

            if (list == null)
            {
                return NotFound();
            }

            return View(new TodoListViewModel
            {
                Id = list.Id,
                Description = list.Description,
                IsActive = list.IsActive
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("Id, Description, IsActive")] TodoListViewModel todoListModel)
        {
            if (id != todoListModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _todosClient.UpdateTodo(id, new Clients.Models.TodoList.UpdateTodoListInputModel
                {
                    Description = todoListModel.Description,
                    IsActive = todoListModel.IsActive
                });

                return RedirectToAction(nameof(Index));
            }

            return View(todoListModel);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var list = await _todosClient.GetById(id);

            if (list == null)
            {
                return NotFound();
            }

            return View(new TodoListViewModel
            {
                Id = list.Id,
                Description = list.Description,
                IsActive = list.IsActive,
                NumberOfTasks = list.NumberOfTasks
            });
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            await _todosClient.DeleteTodo(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Todo.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Todo.Web.Clients.Interfaces;
using Todo.Web.Models;

namespace Todo.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IUserClient _userClient;

        public UsersController(IUserClient userClient)
        {
            _userClient = userClient;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userClient.GetAll();

            var viewModels = users
                .Select(e => new UserViewModel { Id = e.Id, Name = e.Name, IsAdmin = e.IsAdmin })
                .ToArray();

            return View(viewModels);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userClient.GetById(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                IsAdmin = user.IsAdmin
            });
        }

        public IActionResult Create()
        {
            return View();
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Password, IsAdmin")] CreateUserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                await _userClient.CreateUser(new Clients.Models.CreateUserInputModel
                {
                    Name = userViewModel.Name!,
                    Password = userViewModel.Password!,
                    IsAdmin = userViewModel.IsAdmin
                });

                return RedirectToAction(nameof(Index));
            }

            return View(userViewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userClient.GetById(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                IsAdmin = user.IsAdmin
            });
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("Id,Name")] UserViewModel userViewModel)
        {
            if (id != userViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _userClient.UpdateUser(id, new Clients.Models.UpdateUserInputModel
                {
                    Name = userViewModel.Name
                });

                return RedirectToAction(nameof(Index));
            }

            return View(userViewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userClient.GetById(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(new UserViewModel
            {
                Id = user.Id,
                Name = user.Name
            });
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            await _userClient.DeleteUser(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Todo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Todo.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Todo.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todos" asp-action="Index">Todos</a>
                        </li>
                        
                        @if(User.Identity!.IsAuthenticated 
                            && User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav">
                        @if (User.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Todo.Web - Alihan Femi
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>